#define SvGEnum(o) ((GEnum*) SvIV(SvRV(gtk2_perl_check_type(o, "GEnum"))))
#define SvGEnum_nullok(o) (SvROK(o) ? ((GEnum*) SvIV(SvRV(gtk2_perl_check_type(o, "GEnum")))) : NULL)
#define SvGFlags(o) ((GFlags*) SvIV(SvRV(gtk2_perl_check_type(o, "GFlags"))))
#define SvGFlags_nullok(o) (SvROK(o) ? ((GFlags*) SvIV(SvRV(gtk2_perl_check_type(o, "GFlags")))) : NULL)
#define SvGObject(o) ((GObject*) SvIV(SvRV(gtk2_perl_check_type(o, "GObject"))))
#define SvGObject_nullok(o) (SvROK(o) ? ((GObject*) SvIV(SvRV(gtk2_perl_check_type(o, "GObject")))) : NULL)
#define SvGParamSpec(o) ((GParamSpec*) SvIV(SvRV(gtk2_perl_check_type(o, "GParamSpec"))))
#define SvGParamSpec_nullok(o) (SvROK(o) ? ((GParamSpec*) SvIV(SvRV(gtk2_perl_check_type(o, "GParamSpec")))) : NULL)
#define SvGType(o) ((GType*) SvIV(SvRV(gtk2_perl_check_type(o, "GType"))))
#define SvGType_nullok(o) (SvROK(o) ? ((GType*) SvIV(SvRV(gtk2_perl_check_type(o, "GType")))) : NULL)
#define SvGTypeModule(o) ((GTypeModule*) SvIV(SvRV(gtk2_perl_check_type(o, "GTypeModule"))))
#define SvGTypeModule_nullok(o) (SvROK(o) ? ((GTypeModule*) SvIV(SvRV(gtk2_perl_check_type(o, "GTypeModule")))) : NULL)
#define SvGTypePlugin(o) ((GTypePlugin*) SvIV(SvRV(gtk2_perl_check_type(o, "GTypePlugin"))))
#define SvGTypePlugin_nullok(o) (SvROK(o) ? ((GTypePlugin*) SvIV(SvRV(gtk2_perl_check_type(o, "GTypePlugin")))) : NULL)
#define SvGSList(o) ((GSList*) SvIV(SvRV(gtk2_perl_check_type(o, "GSList"))))
#define SvGSList_nullok(o) (SvROK(o) ? ((GSList*) SvIV(SvRV(gtk2_perl_check_type(o, "GSList")))) : NULL)
