#define SvGtkAccelGroup(o) ((GtkAccelGroup*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkAccelGroup"))))
#define SvGtkAccelGroup_nullok(o) (SvROK(o) ? ((GtkAccelGroup*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkAccelGroup")))) : NULL)
#define SvGtkAccelLabel(o) ((GtkAccelLabel*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkAccelLabel"))))
#define SvGtkAccelLabel_nullok(o) (SvROK(o) ? ((GtkAccelLabel*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkAccelLabel")))) : NULL)
#define SvGtkAccessible(o) ((GtkAccessible*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkAccessible"))))
#define SvGtkAccessible_nullok(o) (SvROK(o) ? ((GtkAccessible*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkAccessible")))) : NULL)
#define SvGtkAdjustment(o) ((GtkAdjustment*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkAdjustment"))))
#define SvGtkAdjustment_nullok(o) (SvROK(o) ? ((GtkAdjustment*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkAdjustment")))) : NULL)
#define SvGtkAlignment(o) ((GtkAlignment*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkAlignment"))))
#define SvGtkAlignment_nullok(o) (SvROK(o) ? ((GtkAlignment*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkAlignment")))) : NULL)
#define SvGtkArrow(o) ((GtkArrow*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkArrow"))))
#define SvGtkArrow_nullok(o) (SvROK(o) ? ((GtkArrow*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkArrow")))) : NULL)
#define SvGtkAspectFrame(o) ((GtkAspectFrame*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkAspectFrame"))))
#define SvGtkAspectFrame_nullok(o) (SvROK(o) ? ((GtkAspectFrame*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkAspectFrame")))) : NULL)
#define SvGtkButtonBox(o) ((GtkButtonBox*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkButtonBox"))))
#define SvGtkButtonBox_nullok(o) (SvROK(o) ? ((GtkButtonBox*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkButtonBox")))) : NULL)
#define SvGtkBin(o) ((GtkBin*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkBin"))))
#define SvGtkBin_nullok(o) (SvROK(o) ? ((GtkBin*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkBin")))) : NULL)
#define SvGtkBox(o) ((GtkBox*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkBox"))))
#define SvGtkBox_nullok(o) (SvROK(o) ? ((GtkBox*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkBox")))) : NULL)
#define SvGtkButton(o) ((GtkButton*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkButton"))))
#define SvGtkButton_nullok(o) (SvROK(o) ? ((GtkButton*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkButton")))) : NULL)
#define SvGtkCalendar(o) ((GtkCalendar*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCalendar"))))
#define SvGtkCalendar_nullok(o) (SvROK(o) ? ((GtkCalendar*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCalendar")))) : NULL)
#define SvGtkCellRenderer(o) ((GtkCellRenderer*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCellRenderer"))))
#define SvGtkCellRenderer_nullok(o) (SvROK(o) ? ((GtkCellRenderer*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCellRenderer")))) : NULL)
#define SvGtkCellRendererPixbuf(o) ((GtkCellRendererPixbuf*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCellRendererPixbuf"))))
#define SvGtkCellRendererPixbuf_nullok(o) (SvROK(o) ? ((GtkCellRendererPixbuf*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCellRendererPixbuf")))) : NULL)
#define SvGtkCellRendererText(o) ((GtkCellRendererText*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCellRendererText"))))
#define SvGtkCellRendererText_nullok(o) (SvROK(o) ? ((GtkCellRendererText*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCellRendererText")))) : NULL)
#define SvGtkCellRendererToggle(o) ((GtkCellRendererToggle*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCellRendererToggle"))))
#define SvGtkCellRendererToggle_nullok(o) (SvROK(o) ? ((GtkCellRendererToggle*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCellRendererToggle")))) : NULL)
#define SvGtkCheckButton(o) ((GtkCheckButton*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCheckButton"))))
#define SvGtkCheckButton_nullok(o) (SvROK(o) ? ((GtkCheckButton*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCheckButton")))) : NULL)
#define SvGtkCheckMenuItem(o) ((GtkCheckMenuItem*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCheckMenuItem"))))
#define SvGtkCheckMenuItem_nullok(o) (SvROK(o) ? ((GtkCheckMenuItem*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCheckMenuItem")))) : NULL)
#define SvGtkCList(o) ((GtkCList*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCList"))))
#define SvGtkCList_nullok(o) (SvROK(o) ? ((GtkCList*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCList")))) : NULL)
#define SvGtkColorSelection(o) ((GtkColorSelection*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkColorSelection"))))
#define SvGtkColorSelection_nullok(o) (SvROK(o) ? ((GtkColorSelection*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkColorSelection")))) : NULL)
#define SvGtkColorSelectionDialog(o) ((GtkColorSelectionDialog*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkColorSelectionDialog"))))
#define SvGtkColorSelectionDialog_nullok(o) (SvROK(o) ? ((GtkColorSelectionDialog*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkColorSelectionDialog")))) : NULL)
#define SvGtkCombo(o) ((GtkCombo*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCombo"))))
#define SvGtkCombo_nullok(o) (SvROK(o) ? ((GtkCombo*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCombo")))) : NULL)
#define SvGtkContainer(o) ((GtkContainer*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkContainer"))))
#define SvGtkContainer_nullok(o) (SvROK(o) ? ((GtkContainer*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkContainer")))) : NULL)
#define SvGtkCTree(o) ((GtkCTree*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCTree"))))
#define SvGtkCTree_nullok(o) (SvROK(o) ? ((GtkCTree*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCTree")))) : NULL)
#define SvGtkCurve(o) ((GtkCurve*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCurve"))))
#define SvGtkCurve_nullok(o) (SvROK(o) ? ((GtkCurve*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkCurve")))) : NULL)
#define SvGtkDialog(o) ((GtkDialog*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkDialog"))))
#define SvGtkDialog_nullok(o) (SvROK(o) ? ((GtkDialog*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkDialog")))) : NULL)
#define SvGtkDrawingArea(o) ((GtkDrawingArea*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkDrawingArea"))))
#define SvGtkDrawingArea_nullok(o) (SvROK(o) ? ((GtkDrawingArea*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkDrawingArea")))) : NULL)
#define SvGtkEditable(o) ((GtkEditable*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkEditable"))))
#define SvGtkEditable_nullok(o) (SvROK(o) ? ((GtkEditable*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkEditable")))) : NULL)
#define SvGtkEntry(o) ((GtkEntry*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkEntry"))))
#define SvGtkEntry_nullok(o) (SvROK(o) ? ((GtkEntry*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkEntry")))) : NULL)
#define SvGtkEventBox(o) ((GtkEventBox*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkEventBox"))))
#define SvGtkEventBox_nullok(o) (SvROK(o) ? ((GtkEventBox*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkEventBox")))) : NULL)
#define SvGtkFileSelection(o) ((GtkFileSelection*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkFileSelection"))))
#define SvGtkFileSelection_nullok(o) (SvROK(o) ? ((GtkFileSelection*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkFileSelection")))) : NULL)
#define SvGtkFixed(o) ((GtkFixed*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkFixed"))))
#define SvGtkFixed_nullok(o) (SvROK(o) ? ((GtkFixed*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkFixed")))) : NULL)
#define SvGtkFontSelection(o) ((GtkFontSelection*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkFontSelection"))))
#define SvGtkFontSelection_nullok(o) (SvROK(o) ? ((GtkFontSelection*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkFontSelection")))) : NULL)
#define SvGtkFontSelectionDialog(o) ((GtkFontSelectionDialog*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkFontSelectionDialog"))))
#define SvGtkFontSelectionDialog_nullok(o) (SvROK(o) ? ((GtkFontSelectionDialog*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkFontSelectionDialog")))) : NULL)
#define SvGtkFrame(o) ((GtkFrame*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkFrame"))))
#define SvGtkFrame_nullok(o) (SvROK(o) ? ((GtkFrame*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkFrame")))) : NULL)
#define SvGtkGammaCurve(o) ((GtkGammaCurve*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkGammaCurve"))))
#define SvGtkGammaCurve_nullok(o) (SvROK(o) ? ((GtkGammaCurve*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkGammaCurve")))) : NULL)
#define SvGtkHandleBox(o) ((GtkHandleBox*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkHandleBox"))))
#define SvGtkHandleBox_nullok(o) (SvROK(o) ? ((GtkHandleBox*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkHandleBox")))) : NULL)
#define SvGtkHButtonBox(o) ((GtkHButtonBox*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkHButtonBox"))))
#define SvGtkHButtonBox_nullok(o) (SvROK(o) ? ((GtkHButtonBox*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkHButtonBox")))) : NULL)
#define SvGtkHBox(o) ((GtkHBox*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkHBox"))))
#define SvGtkHBox_nullok(o) (SvROK(o) ? ((GtkHBox*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkHBox")))) : NULL)
#define SvGtkHPaned(o) ((GtkHPaned*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkHPaned"))))
#define SvGtkHPaned_nullok(o) (SvROK(o) ? ((GtkHPaned*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkHPaned")))) : NULL)
#define SvGtkHRuler(o) ((GtkHRuler*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkHRuler"))))
#define SvGtkHRuler_nullok(o) (SvROK(o) ? ((GtkHRuler*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkHRuler")))) : NULL)
#define SvGtkHScale(o) ((GtkHScale*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkHScale"))))
#define SvGtkHScale_nullok(o) (SvROK(o) ? ((GtkHScale*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkHScale")))) : NULL)
#define SvGtkHScrollbar(o) ((GtkHScrollbar*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkHScrollbar"))))
#define SvGtkHScrollbar_nullok(o) (SvROK(o) ? ((GtkHScrollbar*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkHScrollbar")))) : NULL)
#define SvGtkHSeparator(o) ((GtkHSeparator*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkHSeparator"))))
#define SvGtkHSeparator_nullok(o) (SvROK(o) ? ((GtkHSeparator*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkHSeparator")))) : NULL)
#define SvGtkIconFactory(o) ((GtkIconFactory*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkIconFactory"))))
#define SvGtkIconFactory_nullok(o) (SvROK(o) ? ((GtkIconFactory*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkIconFactory")))) : NULL)
#define SvGtkImage(o) ((GtkImage*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkImage"))))
#define SvGtkImage_nullok(o) (SvROK(o) ? ((GtkImage*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkImage")))) : NULL)
#define SvGtkImageMenuItem(o) ((GtkImageMenuItem*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkImageMenuItem"))))
#define SvGtkImageMenuItem_nullok(o) (SvROK(o) ? ((GtkImageMenuItem*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkImageMenuItem")))) : NULL)
#define SvGtkIMContext(o) ((GtkIMContext*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkIMContext"))))
#define SvGtkIMContext_nullok(o) (SvROK(o) ? ((GtkIMContext*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkIMContext")))) : NULL)
#define SvGtkIMContextSimple(o) ((GtkIMContextSimple*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkIMContextSimple"))))
#define SvGtkIMContextSimple_nullok(o) (SvROK(o) ? ((GtkIMContextSimple*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkIMContextSimple")))) : NULL)
#define SvGtkIMMulticontext(o) ((GtkIMMulticontext*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkIMMulticontext"))))
#define SvGtkIMMulticontext_nullok(o) (SvROK(o) ? ((GtkIMMulticontext*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkIMMulticontext")))) : NULL)
#define SvGtkInputDialog(o) ((GtkInputDialog*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkInputDialog"))))
#define SvGtkInputDialog_nullok(o) (SvROK(o) ? ((GtkInputDialog*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkInputDialog")))) : NULL)
#define SvGtkInvisible(o) ((GtkInvisible*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkInvisible"))))
#define SvGtkInvisible_nullok(o) (SvROK(o) ? ((GtkInvisible*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkInvisible")))) : NULL)
#define SvGtkItem(o) ((GtkItem*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkItem"))))
#define SvGtkItem_nullok(o) (SvROK(o) ? ((GtkItem*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkItem")))) : NULL)
#define SvGtkItemFactory(o) ((GtkItemFactory*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkItemFactory"))))
#define SvGtkItemFactory_nullok(o) (SvROK(o) ? ((GtkItemFactory*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkItemFactory")))) : NULL)
#define SvGtkLabel(o) ((GtkLabel*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkLabel"))))
#define SvGtkLabel_nullok(o) (SvROK(o) ? ((GtkLabel*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkLabel")))) : NULL)
#define SvGtkLayout(o) ((GtkLayout*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkLayout"))))
#define SvGtkLayout_nullok(o) (SvROK(o) ? ((GtkLayout*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkLayout")))) : NULL)
#define SvGtkList(o) ((GtkList*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkList"))))
#define SvGtkList_nullok(o) (SvROK(o) ? ((GtkList*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkList")))) : NULL)
#define SvGtkListItem(o) ((GtkListItem*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkListItem"))))
#define SvGtkListItem_nullok(o) (SvROK(o) ? ((GtkListItem*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkListItem")))) : NULL)
#define SvGtkListStore(o) ((GtkListStore*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkListStore"))))
#define SvGtkListStore_nullok(o) (SvROK(o) ? ((GtkListStore*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkListStore")))) : NULL)
#define SvGtkMenu(o) ((GtkMenu*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkMenu"))))
#define SvGtkMenu_nullok(o) (SvROK(o) ? ((GtkMenu*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkMenu")))) : NULL)
#define SvGtkMenuBar(o) ((GtkMenuBar*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkMenuBar"))))
#define SvGtkMenuBar_nullok(o) (SvROK(o) ? ((GtkMenuBar*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkMenuBar")))) : NULL)
#define SvGtkMenuItem(o) ((GtkMenuItem*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkMenuItem"))))
#define SvGtkMenuItem_nullok(o) (SvROK(o) ? ((GtkMenuItem*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkMenuItem")))) : NULL)
#define SvGtkMenuShell(o) ((GtkMenuShell*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkMenuShell"))))
#define SvGtkMenuShell_nullok(o) (SvROK(o) ? ((GtkMenuShell*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkMenuShell")))) : NULL)
#define SvGtkMessageDialog(o) ((GtkMessageDialog*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkMessageDialog"))))
#define SvGtkMessageDialog_nullok(o) (SvROK(o) ? ((GtkMessageDialog*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkMessageDialog")))) : NULL)
#define SvGtkMisc(o) ((GtkMisc*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkMisc"))))
#define SvGtkMisc_nullok(o) (SvROK(o) ? ((GtkMisc*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkMisc")))) : NULL)
#define SvGtkNotebook(o) ((GtkNotebook*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkNotebook"))))
#define SvGtkNotebook_nullok(o) (SvROK(o) ? ((GtkNotebook*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkNotebook")))) : NULL)
#define SvGtkObject(o) ((GtkObject*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkObject"))))
#define SvGtkObject_nullok(o) (SvROK(o) ? ((GtkObject*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkObject")))) : NULL)
#define SvGtkOldEditable(o) ((GtkOldEditable*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkOldEditable"))))
#define SvGtkOldEditable_nullok(o) (SvROK(o) ? ((GtkOldEditable*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkOldEditable")))) : NULL)
#define SvGtkOptionMenu(o) ((GtkOptionMenu*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkOptionMenu"))))
#define SvGtkOptionMenu_nullok(o) (SvROK(o) ? ((GtkOptionMenu*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkOptionMenu")))) : NULL)
#define SvGtkPaned(o) ((GtkPaned*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkPaned"))))
#define SvGtkPaned_nullok(o) (SvROK(o) ? ((GtkPaned*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkPaned")))) : NULL)
#define SvGtkPixmap(o) ((GtkPixmap*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkPixmap"))))
#define SvGtkPixmap_nullok(o) (SvROK(o) ? ((GtkPixmap*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkPixmap")))) : NULL)
#define SvGtkPlug(o) ((GtkPlug*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkPlug"))))
#define SvGtkPlug_nullok(o) (SvROK(o) ? ((GtkPlug*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkPlug")))) : NULL)
#define SvGtkPreview(o) ((GtkPreview*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkPreview"))))
#define SvGtkPreview_nullok(o) (SvROK(o) ? ((GtkPreview*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkPreview")))) : NULL)
#define SvGtkProgress(o) ((GtkProgress*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkProgress"))))
#define SvGtkProgress_nullok(o) (SvROK(o) ? ((GtkProgress*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkProgress")))) : NULL)
#define SvGtkProgressBar(o) ((GtkProgressBar*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkProgressBar"))))
#define SvGtkProgressBar_nullok(o) (SvROK(o) ? ((GtkProgressBar*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkProgressBar")))) : NULL)
#define SvGtkRadioButton(o) ((GtkRadioButton*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkRadioButton"))))
#define SvGtkRadioButton_nullok(o) (SvROK(o) ? ((GtkRadioButton*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkRadioButton")))) : NULL)
#define SvGtkRadioMenuItem(o) ((GtkRadioMenuItem*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkRadioMenuItem"))))
#define SvGtkRadioMenuItem_nullok(o) (SvROK(o) ? ((GtkRadioMenuItem*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkRadioMenuItem")))) : NULL)
#define SvGtkRange(o) ((GtkRange*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkRange"))))
#define SvGtkRange_nullok(o) (SvROK(o) ? ((GtkRange*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkRange")))) : NULL)
#define SvGtkRcStyle(o) ((GtkRcStyle*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkRcStyle"))))
#define SvGtkRcStyle_nullok(o) (SvROK(o) ? ((GtkRcStyle*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkRcStyle")))) : NULL)
#define SvGtkRuler(o) ((GtkRuler*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkRuler"))))
#define SvGtkRuler_nullok(o) (SvROK(o) ? ((GtkRuler*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkRuler")))) : NULL)
#define SvGtkScale(o) ((GtkScale*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkScale"))))
#define SvGtkScale_nullok(o) (SvROK(o) ? ((GtkScale*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkScale")))) : NULL)
#define SvGtkScrollbar(o) ((GtkScrollbar*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkScrollbar"))))
#define SvGtkScrollbar_nullok(o) (SvROK(o) ? ((GtkScrollbar*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkScrollbar")))) : NULL)
#define SvGtkScrolledWindow(o) ((GtkScrolledWindow*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkScrolledWindow"))))
#define SvGtkScrolledWindow_nullok(o) (SvROK(o) ? ((GtkScrolledWindow*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkScrolledWindow")))) : NULL)
#define SvGtkSeparator(o) ((GtkSeparator*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkSeparator"))))
#define SvGtkSeparator_nullok(o) (SvROK(o) ? ((GtkSeparator*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkSeparator")))) : NULL)
#define SvGtkSeparatorMenuItem(o) ((GtkSeparatorMenuItem*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkSeparatorMenuItem"))))
#define SvGtkSeparatorMenuItem_nullok(o) (SvROK(o) ? ((GtkSeparatorMenuItem*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkSeparatorMenuItem")))) : NULL)
#define SvGtkSettings(o) ((GtkSettings*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkSettings"))))
#define SvGtkSettings_nullok(o) (SvROK(o) ? ((GtkSettings*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkSettings")))) : NULL)
#define SvGtkSizeGroup(o) ((GtkSizeGroup*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkSizeGroup"))))
#define SvGtkSizeGroup_nullok(o) (SvROK(o) ? ((GtkSizeGroup*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkSizeGroup")))) : NULL)
#define SvGtkSocket(o) ((GtkSocket*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkSocket"))))
#define SvGtkSocket_nullok(o) (SvROK(o) ? ((GtkSocket*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkSocket")))) : NULL)
#define SvGtkSpinButton(o) ((GtkSpinButton*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkSpinButton"))))
#define SvGtkSpinButton_nullok(o) (SvROK(o) ? ((GtkSpinButton*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkSpinButton")))) : NULL)
#define SvGtkStatusbar(o) ((GtkStatusbar*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkStatusbar"))))
#define SvGtkStatusbar_nullok(o) (SvROK(o) ? ((GtkStatusbar*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkStatusbar")))) : NULL)
#define SvGtkStyle(o) ((GtkStyle*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkStyle"))))
#define SvGtkStyle_nullok(o) (SvROK(o) ? ((GtkStyle*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkStyle")))) : NULL)
#define SvGtkTable(o) ((GtkTable*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTable"))))
#define SvGtkTable_nullok(o) (SvROK(o) ? ((GtkTable*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTable")))) : NULL)
#define SvGtkTearoffMenuItem(o) ((GtkTearoffMenuItem*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTearoffMenuItem"))))
#define SvGtkTearoffMenuItem_nullok(o) (SvROK(o) ? ((GtkTearoffMenuItem*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTearoffMenuItem")))) : NULL)
#define SvGtkText(o) ((GtkText*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkText"))))
#define SvGtkText_nullok(o) (SvROK(o) ? ((GtkText*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkText")))) : NULL)
#define SvGtkTextBuffer(o) ((GtkTextBuffer*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTextBuffer"))))
#define SvGtkTextBuffer_nullok(o) (SvROK(o) ? ((GtkTextBuffer*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTextBuffer")))) : NULL)
#define SvGtkTextChildAnchor(o) ((GtkTextChildAnchor*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTextChildAnchor"))))
#define SvGtkTextChildAnchor_nullok(o) (SvROK(o) ? ((GtkTextChildAnchor*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTextChildAnchor")))) : NULL)
#define SvGtkTextLayout(o) ((GtkTextLayout*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTextLayout"))))
#define SvGtkTextLayout_nullok(o) (SvROK(o) ? ((GtkTextLayout*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTextLayout")))) : NULL)
#define SvGtkTextMark(o) ((GtkTextMark*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTextMark"))))
#define SvGtkTextMark_nullok(o) (SvROK(o) ? ((GtkTextMark*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTextMark")))) : NULL)
#define SvGtkTextTag(o) ((GtkTextTag*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTextTag"))))
#define SvGtkTextTag_nullok(o) (SvROK(o) ? ((GtkTextTag*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTextTag")))) : NULL)
#define SvGtkTextTagTable(o) ((GtkTextTagTable*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTextTagTable"))))
#define SvGtkTextTagTable_nullok(o) (SvROK(o) ? ((GtkTextTagTable*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTextTagTable")))) : NULL)
#define SvGtkTextView(o) ((GtkTextView*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTextView"))))
#define SvGtkTextView_nullok(o) (SvROK(o) ? ((GtkTextView*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTextView")))) : NULL)
#define SvGtkTipsQuery(o) ((GtkTipsQuery*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTipsQuery"))))
#define SvGtkTipsQuery_nullok(o) (SvROK(o) ? ((GtkTipsQuery*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTipsQuery")))) : NULL)
#define SvGtkToggleButton(o) ((GtkToggleButton*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkToggleButton"))))
#define SvGtkToggleButton_nullok(o) (SvROK(o) ? ((GtkToggleButton*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkToggleButton")))) : NULL)
#define SvGtkToolbar(o) ((GtkToolbar*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkToolbar"))))
#define SvGtkToolbar_nullok(o) (SvROK(o) ? ((GtkToolbar*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkToolbar")))) : NULL)
#define SvGtkTooltips(o) ((GtkTooltips*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTooltips"))))
#define SvGtkTooltips_nullok(o) (SvROK(o) ? ((GtkTooltips*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTooltips")))) : NULL)
#define SvGtkTree(o) ((GtkTree*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTree"))))
#define SvGtkTree_nullok(o) (SvROK(o) ? ((GtkTree*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTree")))) : NULL)
#define SvGtkTreeItem(o) ((GtkTreeItem*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTreeItem"))))
#define SvGtkTreeItem_nullok(o) (SvROK(o) ? ((GtkTreeItem*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTreeItem")))) : NULL)
#define SvGtkTreeModelSort(o) ((GtkTreeModelSort*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTreeModelSort"))))
#define SvGtkTreeModelSort_nullok(o) (SvROK(o) ? ((GtkTreeModelSort*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTreeModelSort")))) : NULL)
#define SvGtkTreeSelection(o) ((GtkTreeSelection*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTreeSelection"))))
#define SvGtkTreeSelection_nullok(o) (SvROK(o) ? ((GtkTreeSelection*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTreeSelection")))) : NULL)
#define SvGtkTreeStore(o) ((GtkTreeStore*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTreeStore"))))
#define SvGtkTreeStore_nullok(o) (SvROK(o) ? ((GtkTreeStore*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTreeStore")))) : NULL)
#define SvGtkTreeView(o) ((GtkTreeView*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTreeView"))))
#define SvGtkTreeView_nullok(o) (SvROK(o) ? ((GtkTreeView*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTreeView")))) : NULL)
#define SvGtkTreeViewColumn(o) ((GtkTreeViewColumn*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTreeViewColumn"))))
#define SvGtkTreeViewColumn_nullok(o) (SvROK(o) ? ((GtkTreeViewColumn*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTreeViewColumn")))) : NULL)
#define SvGtkVButtonBox(o) ((GtkVButtonBox*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkVButtonBox"))))
#define SvGtkVButtonBox_nullok(o) (SvROK(o) ? ((GtkVButtonBox*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkVButtonBox")))) : NULL)
#define SvGtkVBox(o) ((GtkVBox*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkVBox"))))
#define SvGtkVBox_nullok(o) (SvROK(o) ? ((GtkVBox*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkVBox")))) : NULL)
#define SvGtkViewport(o) ((GtkViewport*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkViewport"))))
#define SvGtkViewport_nullok(o) (SvROK(o) ? ((GtkViewport*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkViewport")))) : NULL)
#define SvGtkVPaned(o) ((GtkVPaned*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkVPaned"))))
#define SvGtkVPaned_nullok(o) (SvROK(o) ? ((GtkVPaned*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkVPaned")))) : NULL)
#define SvGtkVRuler(o) ((GtkVRuler*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkVRuler"))))
#define SvGtkVRuler_nullok(o) (SvROK(o) ? ((GtkVRuler*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkVRuler")))) : NULL)
#define SvGtkVScale(o) ((GtkVScale*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkVScale"))))
#define SvGtkVScale_nullok(o) (SvROK(o) ? ((GtkVScale*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkVScale")))) : NULL)
#define SvGtkVScrollbar(o) ((GtkVScrollbar*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkVScrollbar"))))
#define SvGtkVScrollbar_nullok(o) (SvROK(o) ? ((GtkVScrollbar*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkVScrollbar")))) : NULL)
#define SvGtkVSeparator(o) ((GtkVSeparator*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkVSeparator"))))
#define SvGtkVSeparator_nullok(o) (SvROK(o) ? ((GtkVSeparator*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkVSeparator")))) : NULL)
#define SvGtkWidget(o) ((GtkWidget*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkWidget"))))
#define SvGtkWidget_nullok(o) (SvROK(o) ? ((GtkWidget*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkWidget")))) : NULL)
#define SvGtkWindow(o) ((GtkWindow*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkWindow"))))
#define SvGtkWindow_nullok(o) (SvROK(o) ? ((GtkWindow*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkWindow")))) : NULL)
#define SvGtkWindowGroup(o) ((GtkWindowGroup*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkWindowGroup"))))
#define SvGtkWindowGroup_nullok(o) (SvROK(o) ? ((GtkWindowGroup*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkWindowGroup")))) : NULL)
#define SvGtkRequisition(o) ((GtkRequisition*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkRequisition"))))
#define SvGtkRequisition_nullok(o) (SvROK(o) ? ((GtkRequisition*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkRequisition")))) : NULL)
#define SvGtkBoxChild(o) ((GtkBoxChild*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkBoxChild"))))
#define SvGtkBoxChild_nullok(o) (SvROK(o) ? ((GtkBoxChild*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkBoxChild")))) : NULL)
#define SvGtkIconSet(o) ((GtkIconSet*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkIconSet"))))
#define SvGtkIconSet_nullok(o) (SvROK(o) ? ((GtkIconSet*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkIconSet")))) : NULL)
#define SvGtkIconSource(o) ((GtkIconSource*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkIconSource"))))
#define SvGtkIconSource_nullok(o) (SvROK(o) ? ((GtkIconSource*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkIconSource")))) : NULL)
#define SvGtkSelectionData(o) ((GtkSelectionData*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkSelectionData"))))
#define SvGtkSelectionData_nullok(o) (SvROK(o) ? ((GtkSelectionData*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkSelectionData")))) : NULL)
#define SvGtkTextIter(o) ((GtkTextIter*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTextIter"))))
#define SvGtkTextIter_nullok(o) (SvROK(o) ? ((GtkTextIter*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTextIter")))) : NULL)
#define SvGtkTreeIter(o) ((GtkTreeIter*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTreeIter"))))
#define SvGtkTreeIter_nullok(o) (SvROK(o) ? ((GtkTreeIter*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTreeIter")))) : NULL)
#define SvGtkTreeModel(o) ((GtkTreeModel*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTreeModel"))))
#define SvGtkTreeModel_nullok(o) (SvROK(o) ? ((GtkTreeModel*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTreeModel")))) : NULL)
#define SvGtkTreePath(o) ((GtkTreePath*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTreePath"))))
#define SvGtkTreePath_nullok(o) (SvROK(o) ? ((GtkTreePath*) SvIV(SvRV(gtk2_perl_check_type(o, "GtkTreePath")))) : NULL)
#define SvGtkAccelFlags(o) gtk2_perl_convert_flags(GTK_TYPE_ACCEL_FLAGS, o)
#define newSVGtkAccelFlags(o) gtk2_perl_convert_back_flags(GTK_TYPE_ACCEL_FLAGS, o)
#define SvGtkCalendarDisplayOptions(o) gtk2_perl_convert_flags(GTK_TYPE_CALENDAR_DISPLAY_OPTIONS, o)
#define newSVGtkCalendarDisplayOptions(o) gtk2_perl_convert_back_flags(GTK_TYPE_CALENDAR_DISPLAY_OPTIONS, o)
#define SvGtkCellRendererState(o) gtk2_perl_convert_flags(GTK_TYPE_CELL_RENDERER_STATE, o)
#define newSVGtkCellRendererState(o) gtk2_perl_convert_back_flags(GTK_TYPE_CELL_RENDERER_STATE, o)
#define SvGtkCellRendererMode(o) gtk2_perl_convert_enum(GTK_TYPE_CELL_RENDERER_MODE, o)
#define newSVGtkCellRendererMode(o) gtk2_perl_convert_back_enum(GTK_TYPE_CELL_RENDERER_MODE, o)
#define SvGtkCellType(o) gtk2_perl_convert_enum(GTK_TYPE_CELL_TYPE, o)
#define newSVGtkCellType(o) gtk2_perl_convert_back_enum(GTK_TYPE_CELL_TYPE, o)
#define SvGtkCListDragPos(o) gtk2_perl_convert_enum(GTK_TYPE_CLIST_DRAG_POS, o)
#define newSVGtkCListDragPos(o) gtk2_perl_convert_back_enum(GTK_TYPE_CLIST_DRAG_POS, o)
#define SvGtkButtonAction(o) gtk2_perl_convert_flags(GTK_TYPE_BUTTON_ACTION, o)
#define newSVGtkButtonAction(o) gtk2_perl_convert_back_flags(GTK_TYPE_BUTTON_ACTION, o)
#define SvGtkCTreePos(o) gtk2_perl_convert_enum(GTK_TYPE_CTREE_POS, o)
#define newSVGtkCTreePos(o) gtk2_perl_convert_back_enum(GTK_TYPE_CTREE_POS, o)
#define SvGtkCTreeLineStyle(o) gtk2_perl_convert_enum(GTK_TYPE_CTREE_LINE_STYLE, o)
#define newSVGtkCTreeLineStyle(o) gtk2_perl_convert_back_enum(GTK_TYPE_CTREE_LINE_STYLE, o)
#define SvGtkCTreeExpanderStyle(o) gtk2_perl_convert_enum(GTK_TYPE_CTREE_EXPANDER_STYLE, o)
#define newSVGtkCTreeExpanderStyle(o) gtk2_perl_convert_back_enum(GTK_TYPE_CTREE_EXPANDER_STYLE, o)
#define SvGtkCTreeExpansionType(o) gtk2_perl_convert_enum(GTK_TYPE_CTREE_EXPANSION_TYPE, o)
#define newSVGtkCTreeExpansionType(o) gtk2_perl_convert_back_enum(GTK_TYPE_CTREE_EXPANSION_TYPE, o)
#define SvGtkDebugFlag(o) gtk2_perl_convert_flags(GTK_TYPE_DEBUG_FLAG, o)
#define newSVGtkDebugFlag(o) gtk2_perl_convert_back_flags(GTK_TYPE_DEBUG_FLAG, o)
#define SvGtkDialogFlags(o) gtk2_perl_convert_flags(GTK_TYPE_DIALOG_FLAGS, o)
#define newSVGtkDialogFlags(o) gtk2_perl_convert_back_flags(GTK_TYPE_DIALOG_FLAGS, o)
#define SvGtkResponseType(o) gtk2_perl_convert_enum(GTK_TYPE_RESPONSE_TYPE, o)
#define newSVGtkResponseType(o) gtk2_perl_convert_back_enum(GTK_TYPE_RESPONSE_TYPE, o)
#define SvGtkDestDefaults(o) gtk2_perl_convert_flags(GTK_TYPE_DEST_DEFAULTS, o)
#define newSVGtkDestDefaults(o) gtk2_perl_convert_back_flags(GTK_TYPE_DEST_DEFAULTS, o)
#define SvGtkTargetFlags(o) gtk2_perl_convert_flags(GTK_TYPE_TARGET_FLAGS, o)
#define newSVGtkTargetFlags(o) gtk2_perl_convert_back_flags(GTK_TYPE_TARGET_FLAGS, o)
#define SvGtkAnchorType(o) gtk2_perl_convert_enum(GTK_TYPE_ANCHOR_TYPE, o)
#define newSVGtkAnchorType(o) gtk2_perl_convert_back_enum(GTK_TYPE_ANCHOR_TYPE, o)
#define SvGtkArrowType(o) gtk2_perl_convert_enum(GTK_TYPE_ARROW_TYPE, o)
#define newSVGtkArrowType(o) gtk2_perl_convert_back_enum(GTK_TYPE_ARROW_TYPE, o)
#define SvGtkAttachOptions(o) gtk2_perl_convert_flags(GTK_TYPE_ATTACH_OPTIONS, o)
#define newSVGtkAttachOptions(o) gtk2_perl_convert_back_flags(GTK_TYPE_ATTACH_OPTIONS, o)
#define SvGtkButtonBoxStyle(o) gtk2_perl_convert_enum(GTK_TYPE_BUTTON_BOX_STYLE, o)
#define newSVGtkButtonBoxStyle(o) gtk2_perl_convert_back_enum(GTK_TYPE_BUTTON_BOX_STYLE, o)
#define SvGtkCurveType(o) gtk2_perl_convert_enum(GTK_TYPE_CURVE_TYPE, o)
#define newSVGtkCurveType(o) gtk2_perl_convert_back_enum(GTK_TYPE_CURVE_TYPE, o)
#define SvGtkDeleteType(o) gtk2_perl_convert_enum(GTK_TYPE_DELETE_TYPE, o)
#define newSVGtkDeleteType(o) gtk2_perl_convert_back_enum(GTK_TYPE_DELETE_TYPE, o)
#define SvGtkDirectionType(o) gtk2_perl_convert_enum(GTK_TYPE_DIRECTION_TYPE, o)
#define newSVGtkDirectionType(o) gtk2_perl_convert_back_enum(GTK_TYPE_DIRECTION_TYPE, o)
#define SvGtkExpanderStyle(o) gtk2_perl_convert_enum(GTK_TYPE_EXPANDER_STYLE, o)
#define newSVGtkExpanderStyle(o) gtk2_perl_convert_back_enum(GTK_TYPE_EXPANDER_STYLE, o)
#define SvGtkIconSize(o) gtk2_perl_convert_enum(GTK_TYPE_ICON_SIZE, o)
#define newSVGtkIconSize(o) gtk2_perl_convert_back_enum(GTK_TYPE_ICON_SIZE, o)
#define SvGtkSideType(o) gtk2_perl_convert_enum(GTK_TYPE_SIDE_TYPE, o)
#define newSVGtkSideType(o) gtk2_perl_convert_back_enum(GTK_TYPE_SIDE_TYPE, o)
#define SvGtkTextDirection(o) gtk2_perl_convert_enum(GTK_TYPE_TEXT_DIRECTION, o)
#define newSVGtkTextDirection(o) gtk2_perl_convert_back_enum(GTK_TYPE_TEXT_DIRECTION, o)
#define SvGtkJustification(o) gtk2_perl_convert_enum(GTK_TYPE_JUSTIFICATION, o)
#define newSVGtkJustification(o) gtk2_perl_convert_back_enum(GTK_TYPE_JUSTIFICATION, o)
#define SvGtkMatchType(o) gtk2_perl_convert_enum(GTK_TYPE_MATCH_TYPE, o)
#define newSVGtkMatchType(o) gtk2_perl_convert_back_enum(GTK_TYPE_MATCH_TYPE, o)
#define SvGtkMenuDirectionType(o) gtk2_perl_convert_enum(GTK_TYPE_MENU_DIRECTION_TYPE, o)
#define newSVGtkMenuDirectionType(o) gtk2_perl_convert_back_enum(GTK_TYPE_MENU_DIRECTION_TYPE, o)
#define SvGtkMetricType(o) gtk2_perl_convert_enum(GTK_TYPE_METRIC_TYPE, o)
#define newSVGtkMetricType(o) gtk2_perl_convert_back_enum(GTK_TYPE_METRIC_TYPE, o)
#define SvGtkMovementStep(o) gtk2_perl_convert_enum(GTK_TYPE_MOVEMENT_STEP, o)
#define newSVGtkMovementStep(o) gtk2_perl_convert_back_enum(GTK_TYPE_MOVEMENT_STEP, o)
#define SvGtkOrientation(o) gtk2_perl_convert_enum(GTK_TYPE_ORIENTATION, o)
#define newSVGtkOrientation(o) gtk2_perl_convert_back_enum(GTK_TYPE_ORIENTATION, o)
#define SvGtkCornerType(o) gtk2_perl_convert_enum(GTK_TYPE_CORNER_TYPE, o)
#define newSVGtkCornerType(o) gtk2_perl_convert_back_enum(GTK_TYPE_CORNER_TYPE, o)
#define SvGtkPackType(o) gtk2_perl_convert_enum(GTK_TYPE_PACK_TYPE, o)
#define newSVGtkPackType(o) gtk2_perl_convert_back_enum(GTK_TYPE_PACK_TYPE, o)
#define SvGtkPathPriorityType(o) gtk2_perl_convert_enum(GTK_TYPE_PATH_PRIORITY_TYPE, o)
#define newSVGtkPathPriorityType(o) gtk2_perl_convert_back_enum(GTK_TYPE_PATH_PRIORITY_TYPE, o)
#define SvGtkPathType(o) gtk2_perl_convert_enum(GTK_TYPE_PATH_TYPE, o)
#define newSVGtkPathType(o) gtk2_perl_convert_back_enum(GTK_TYPE_PATH_TYPE, o)
#define SvGtkPolicyType(o) gtk2_perl_convert_enum(GTK_TYPE_POLICY_TYPE, o)
#define newSVGtkPolicyType(o) gtk2_perl_convert_back_enum(GTK_TYPE_POLICY_TYPE, o)
#define SvGtkPositionType(o) gtk2_perl_convert_enum(GTK_TYPE_POSITION_TYPE, o)
#define newSVGtkPositionType(o) gtk2_perl_convert_back_enum(GTK_TYPE_POSITION_TYPE, o)
#define SvGtkPreviewType(o) gtk2_perl_convert_enum(GTK_TYPE_PREVIEW_TYPE, o)
#define newSVGtkPreviewType(o) gtk2_perl_convert_back_enum(GTK_TYPE_PREVIEW_TYPE, o)
#define SvGtkReliefStyle(o) gtk2_perl_convert_enum(GTK_TYPE_RELIEF_STYLE, o)
#define newSVGtkReliefStyle(o) gtk2_perl_convert_back_enum(GTK_TYPE_RELIEF_STYLE, o)
#define SvGtkResizeMode(o) gtk2_perl_convert_enum(GTK_TYPE_RESIZE_MODE, o)
#define newSVGtkResizeMode(o) gtk2_perl_convert_back_enum(GTK_TYPE_RESIZE_MODE, o)
#define SvGtkScrollType(o) gtk2_perl_convert_enum(GTK_TYPE_SCROLL_TYPE, o)
#define newSVGtkScrollType(o) gtk2_perl_convert_back_enum(GTK_TYPE_SCROLL_TYPE, o)
#define SvGtkSelectionMode(o) gtk2_perl_convert_enum(GTK_TYPE_SELECTION_MODE, o)
#define newSVGtkSelectionMode(o) gtk2_perl_convert_back_enum(GTK_TYPE_SELECTION_MODE, o)
#define SvGtkShadowType(o) gtk2_perl_convert_enum(GTK_TYPE_SHADOW_TYPE, o)
#define newSVGtkShadowType(o) gtk2_perl_convert_back_enum(GTK_TYPE_SHADOW_TYPE, o)
#define SvGtkStateType(o) gtk2_perl_convert_enum(GTK_TYPE_STATE_TYPE, o)
#define newSVGtkStateType(o) gtk2_perl_convert_back_enum(GTK_TYPE_STATE_TYPE, o)
#define SvGtkSubmenuDirection(o) gtk2_perl_convert_enum(GTK_TYPE_SUBMENU_DIRECTION, o)
#define newSVGtkSubmenuDirection(o) gtk2_perl_convert_back_enum(GTK_TYPE_SUBMENU_DIRECTION, o)
#define SvGtkSubmenuPlacement(o) gtk2_perl_convert_enum(GTK_TYPE_SUBMENU_PLACEMENT, o)
#define newSVGtkSubmenuPlacement(o) gtk2_perl_convert_back_enum(GTK_TYPE_SUBMENU_PLACEMENT, o)
#define SvGtkToolbarStyle(o) gtk2_perl_convert_enum(GTK_TYPE_TOOLBAR_STYLE, o)
#define newSVGtkToolbarStyle(o) gtk2_perl_convert_back_enum(GTK_TYPE_TOOLBAR_STYLE, o)
#define SvGtkUpdateType(o) gtk2_perl_convert_enum(GTK_TYPE_UPDATE_TYPE, o)
#define newSVGtkUpdateType(o) gtk2_perl_convert_back_enum(GTK_TYPE_UPDATE_TYPE, o)
#define SvGtkVisibility(o) gtk2_perl_convert_enum(GTK_TYPE_VISIBILITY, o)
#define newSVGtkVisibility(o) gtk2_perl_convert_back_enum(GTK_TYPE_VISIBILITY, o)
#define SvGtkWindowPosition(o) gtk2_perl_convert_enum(GTK_TYPE_WINDOW_POSITION, o)
#define newSVGtkWindowPosition(o) gtk2_perl_convert_back_enum(GTK_TYPE_WINDOW_POSITION, o)
#define SvGtkWindowType(o) gtk2_perl_convert_enum(GTK_TYPE_WINDOW_TYPE, o)
#define newSVGtkWindowType(o) gtk2_perl_convert_back_enum(GTK_TYPE_WINDOW_TYPE, o)
#define SvGtkWrapMode(o) gtk2_perl_convert_enum(GTK_TYPE_WRAP_MODE, o)
#define newSVGtkWrapMode(o) gtk2_perl_convert_back_enum(GTK_TYPE_WRAP_MODE, o)
#define SvGtkSortType(o) gtk2_perl_convert_enum(GTK_TYPE_SORT_TYPE, o)
#define newSVGtkSortType(o) gtk2_perl_convert_back_enum(GTK_TYPE_SORT_TYPE, o)
#define SvGtkImageType(o) gtk2_perl_convert_enum(GTK_TYPE_IMAGE_TYPE, o)
#define newSVGtkImageType(o) gtk2_perl_convert_back_enum(GTK_TYPE_IMAGE_TYPE, o)
#define SvGtkMessageType(o) gtk2_perl_convert_enum(GTK_TYPE_MESSAGE_TYPE, o)
#define newSVGtkMessageType(o) gtk2_perl_convert_back_enum(GTK_TYPE_MESSAGE_TYPE, o)
#define SvGtkButtonsType(o) gtk2_perl_convert_enum(GTK_TYPE_BUTTONS_TYPE, o)
#define newSVGtkButtonsType(o) gtk2_perl_convert_back_enum(GTK_TYPE_BUTTONS_TYPE, o)
#define SvGtkNotebookTab(o) gtk2_perl_convert_enum(GTK_TYPE_NOTEBOOK_TAB, o)
#define newSVGtkNotebookTab(o) gtk2_perl_convert_back_enum(GTK_TYPE_NOTEBOOK_TAB, o)
#define SvGtkObjectFlags(o) gtk2_perl_convert_flags(GTK_TYPE_OBJECT_FLAGS, o)
#define newSVGtkObjectFlags(o) gtk2_perl_convert_back_flags(GTK_TYPE_OBJECT_FLAGS, o)
#define SvGtkArgFlags(o) gtk2_perl_convert_flags(GTK_TYPE_ARG_FLAGS, o)
#define newSVGtkArgFlags(o) gtk2_perl_convert_back_flags(GTK_TYPE_ARG_FLAGS, o)
#define SvGtkPrivateFlags(o) gtk2_perl_convert_flags(GTK_TYPE_PRIVATE_FLAGS, o)
#define newSVGtkPrivateFlags(o) gtk2_perl_convert_back_flags(GTK_TYPE_PRIVATE_FLAGS, o)
#define SvGtkProgressBarStyle(o) gtk2_perl_convert_enum(GTK_TYPE_PROGRESS_BAR_STYLE, o)
#define newSVGtkProgressBarStyle(o) gtk2_perl_convert_back_enum(GTK_TYPE_PROGRESS_BAR_STYLE, o)
#define SvGtkProgressBarOrientation(o) gtk2_perl_convert_enum(GTK_TYPE_PROGRESS_BAR_ORIENTATION, o)
#define newSVGtkProgressBarOrientation(o) gtk2_perl_convert_back_enum(GTK_TYPE_PROGRESS_BAR_ORIENTATION, o)
#define SvGtkRcFlags(o) gtk2_perl_convert_flags(GTK_TYPE_RC_FLAGS, o)
#define newSVGtkRcFlags(o) gtk2_perl_convert_back_flags(GTK_TYPE_RC_FLAGS, o)
#define SvGtkRcTokenType(o) gtk2_perl_convert_enum(GTK_TYPE_RC_TOKEN_TYPE, o)
#define newSVGtkRcTokenType(o) gtk2_perl_convert_back_enum(GTK_TYPE_RC_TOKEN_TYPE, o)
#define SvGtkSizeGroupMode(o) gtk2_perl_convert_enum(GTK_TYPE_SIZE_GROUP_MODE, o)
#define newSVGtkSizeGroupMode(o) gtk2_perl_convert_back_enum(GTK_TYPE_SIZE_GROUP_MODE, o)
#define SvGtkSpinButtonUpdatePolicy(o) gtk2_perl_convert_enum(GTK_TYPE_SPIN_BUTTON_UPDATE_POLICY, o)
#define newSVGtkSpinButtonUpdatePolicy(o) gtk2_perl_convert_back_enum(GTK_TYPE_SPIN_BUTTON_UPDATE_POLICY, o)
#define SvGtkSpinType(o) gtk2_perl_convert_enum(GTK_TYPE_SPIN_TYPE, o)
#define newSVGtkSpinType(o) gtk2_perl_convert_back_enum(GTK_TYPE_SPIN_TYPE, o)
#define SvGtkTextSearchFlags(o) gtk2_perl_convert_enum(GTK_TYPE_TEXT_SEARCH_FLAGS, o)
#define newSVGtkTextSearchFlags(o) gtk2_perl_convert_back_enum(GTK_TYPE_TEXT_SEARCH_FLAGS, o)
#define SvGtkTextWindowType(o) gtk2_perl_convert_enum(GTK_TYPE_TEXT_WINDOW_TYPE, o)
#define newSVGtkTextWindowType(o) gtk2_perl_convert_back_enum(GTK_TYPE_TEXT_WINDOW_TYPE, o)
#define SvGtkToolbarChildType(o) gtk2_perl_convert_enum(GTK_TYPE_TOOLBAR_CHILD_TYPE, o)
#define newSVGtkToolbarChildType(o) gtk2_perl_convert_back_enum(GTK_TYPE_TOOLBAR_CHILD_TYPE, o)
#define SvGtkToolbarSpaceStyle(o) gtk2_perl_convert_enum(GTK_TYPE_TOOLBAR_SPACE_STYLE, o)
#define newSVGtkToolbarSpaceStyle(o) gtk2_perl_convert_back_enum(GTK_TYPE_TOOLBAR_SPACE_STYLE, o)
#define SvGtkTreeViewMode(o) gtk2_perl_convert_enum(GTK_TYPE_TREE_VIEW_MODE, o)
#define newSVGtkTreeViewMode(o) gtk2_perl_convert_back_enum(GTK_TYPE_TREE_VIEW_MODE, o)
#define SvGtkTreeModelFlags(o) gtk2_perl_convert_flags(GTK_TYPE_TREE_MODEL_FLAGS, o)
#define newSVGtkTreeModelFlags(o) gtk2_perl_convert_back_flags(GTK_TYPE_TREE_MODEL_FLAGS, o)
#define SvGtkTreeViewColumnSizing(o) gtk2_perl_convert_enum(GTK_TYPE_TREE_VIEW_COLUMN_SIZING, o)
#define newSVGtkTreeViewColumnSizing(o) gtk2_perl_convert_back_enum(GTK_TYPE_TREE_VIEW_COLUMN_SIZING, o)
#define SvGtkTreeViewDropPosition(o) gtk2_perl_convert_enum(GTK_TYPE_TREE_VIEW_DROP_POSITION, o)
#define newSVGtkTreeViewDropPosition(o) gtk2_perl_convert_back_enum(GTK_TYPE_TREE_VIEW_DROP_POSITION, o)
#define SvGtkWidgetFlags(o) gtk2_perl_convert_flags(GTK_TYPE_WIDGET_FLAGS, o)
#define newSVGtkWidgetFlags(o) gtk2_perl_convert_back_flags(GTK_TYPE_WIDGET_FLAGS, o)
#define SvGtkWidgetHelpType(o) gtk2_perl_convert_enum(GTK_TYPE_WIDGET_HELP_TYPE, o)
#define newSVGtkWidgetHelpType(o) gtk2_perl_convert_back_enum(GTK_TYPE_WIDGET_HELP_TYPE, o)
