#define SvAtkGObjectAccessible(o) ((AtkGObjectAccessible*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkGObjectAccessible"))))
#define SvAtkGObjectAccessible_nullok(o) (SvROK(o) ? ((AtkGObjectAccessible*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkGObjectAccessible")))) : NULL)
#define SvAtkHyperlink(o) ((AtkHyperlink*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkHyperlink"))))
#define SvAtkHyperlink_nullok(o) (SvROK(o) ? ((AtkHyperlink*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkHyperlink")))) : NULL)
#define SvAtkNoOpObject(o) ((AtkNoOpObject*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkNoOpObject"))))
#define SvAtkNoOpObject_nullok(o) (SvROK(o) ? ((AtkNoOpObject*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkNoOpObject")))) : NULL)
#define SvAtkNoOpObjectFactory(o) ((AtkNoOpObjectFactory*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkNoOpObjectFactory"))))
#define SvAtkNoOpObjectFactory_nullok(o) (SvROK(o) ? ((AtkNoOpObjectFactory*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkNoOpObjectFactory")))) : NULL)
#define SvAtkObject(o) ((AtkObject*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkObject"))))
#define SvAtkObject_nullok(o) (SvROK(o) ? ((AtkObject*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkObject")))) : NULL)
#define SvAtkObjectFactory(o) ((AtkObjectFactory*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkObjectFactory"))))
#define SvAtkObjectFactory_nullok(o) (SvROK(o) ? ((AtkObjectFactory*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkObjectFactory")))) : NULL)
#define SvAtkRegistry(o) ((AtkRegistry*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkRegistry"))))
#define SvAtkRegistry_nullok(o) (SvROK(o) ? ((AtkRegistry*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkRegistry")))) : NULL)
#define SvAtkRelation(o) ((AtkRelation*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkRelation"))))
#define SvAtkRelation_nullok(o) (SvROK(o) ? ((AtkRelation*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkRelation")))) : NULL)
#define SvAtkRelationSet(o) ((AtkRelationSet*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkRelationSet"))))
#define SvAtkRelationSet_nullok(o) (SvROK(o) ? ((AtkRelationSet*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkRelationSet")))) : NULL)
#define SvAtkStateSet(o) ((AtkStateSet*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkStateSet"))))
#define SvAtkStateSet_nullok(o) (SvROK(o) ? ((AtkStateSet*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkStateSet")))) : NULL)
#define SvAtkUtil(o) ((AtkUtil*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkUtil"))))
#define SvAtkUtil_nullok(o) (SvROK(o) ? ((AtkUtil*) SvIV(SvRV(gtk2_perl_check_type(o, "AtkUtil")))) : NULL)
